import sprite from "../assets/icons/spire.svg";

const About = () => {
  return (
    <section className="px-8 flex flex-col items-center gap-10">
      <h2 className="font-right text-white text-[28px] leading-none -tracking-wide uppercase break-normal w-[75%]">
        a Story that started with{" "}
        <span className="text-accent">
          one simple <br /> ape
        </span>
      </h2>
      <p className="font-messina text-base font-normal text-white text-right leading-[1.19]  w-[75%]">
        WHO GOT
        <br />
        FED UP WITH BORING
        <br />
        AND HYPOCRITIC
        <br />
        COMMONPLACE THIS IS
        <br />
        HOW THE IDEA OF
        <br />
        ESCAPING AND DYNAMIC
        <br />
        JOURNEY ON THE YACHT
      </p>

      <div className="w-[75%] flex flex-col items-center">
        <svg className="w-6 h-6 mb-4">
          <use href={`${sprite}#icon-sharp`}></use>
        </svg>
        <p className="font-messina text-xs font-normal text-white text-center leading-[1.17]">
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </p>
      </div>
    </section>
  );
};

export default About;
