import aboutApe from "../assets/img/aboutApe.webp";
import XTextBlock from "./XTextBlock";
const About = () => {
  return (
    <section className="px-8 flex flex-col items-center gap-10 mb-[60px]">
      <h2 className="text-white text-[28px] leading-none -tracking-wide uppercase break-normal w-[75%]">
        a Story that started with{" "}
        <span className="text-accent">
          one simple <br /> ape
        </span>
      </h2>
      <p className="font-messina text-base font-light text-white text-right leading-[1.19]  w-[75%]">
        WHO GOT
        <br />
        FED UP WITH BORING
        <br />
        AND HYPOCRITIC
        <br />
        COMMONPLACE THIS IS
        <br />
        HOW THE IDEA OF
        <br />
        ESCAPING AND DYNAMIC
        <br />
        JOURNEY ON THE YACHT
      </p>

      <XTextBlock
        xSize="24"
        text="EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
        RANDOMLY GENERATED BY USERS"
        lineHeight="1.14"
        textSize="text-xs"
      />
      <div className="w-[75%] flex flex-col items-center">
        <img src={aboutApe} alt="ape in admiral cap" />
        <div className="w-full h-5 bg-accent "></div>
      </div>
    </section>
  );
};

export default About;
